FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

# Copiar archivos de proyecto
COPY shared/*.csproj ./shared/
COPY worker/*.csproj ./worker/
RUN dotnet restore worker/worker.csproj

# Copiar código
COPY . .

WORKDIR /app/worker
CMD ["dotnet", "run"]