FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

# Copiar archivos de proyecto para cachear restore
COPY shared/*.csproj ./shared/
COPY backend/*.csproj ./backend/
RUN dotnet restore backend/backend.csproj

# Copiar resto del código
COPY . .

WORKDIR /app/backend
EXPOSE 8080

# Usamos dotnet run para desarrollo, ya que tienes el SDK
CMD ["dotnet", "run", "--urls", "http://0.0.0.0:8080"]